apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: php-pvc
    labels:
        name: php-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
    name: php-pod
    labels:
        env: testing
        region: IN
        app: php
spec:
    containers:
    - name: myphp-con
      image: saurabh43800/apache-webserver-php:v4
      volumeMounts:
      - name: php-vol
        mountPath: /var/www/html
    volumes:
    - name: php-vol
      persistentVolumeClaim:
        claimName: php-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: php-svc
  labels:
    app: php
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30001
    port: 81
    targetPort: 80
  selector:
    app: php
---
